[package]
name = "bandit"
version = "0.3.2"
edition = "2024"
repository = "https://github.com/That-H/bandit"

[dependencies]
crossterm = "0.29.0"
point = { git = "https://github.com/That-H/point/", branch = "master" }
