[package]
name = "bandit"
version = "0.3.3"
edition = "2024"
repository = "https://github.com/That-H/bandit"

[dependencies]
crossterm = "0.29.0"
point = { git = "https://github.com/That-H/point/", tag = "0.6.1" }
